---
permalink: pretty
markdown: kramdown
exclude:
- Gem*
- "*.lock"
- "*rb"
- ".git*"
- "*.md"
- "*.json"
- node_modules
- vendor
- gulp*
- ".jekyll-metadata"
- ".*"
timezone: UTC
author: Dieter Peirs
title: Inuit boilerplate
description: A Jekyll boilerplate.
url: none
email: hello@dieterpeirs.com
address: 'Henri Dunantlaan 18/402'
city: '9000 Ghent'
phone: '+32 (0) 479 79 76 74'
btw: 'BE0663.754.370'
twitter_username: DieterPeirs
github_username: dietr
dribbble_username: DieterPeirs
medium_username: "@DieterPeirs"
google_analytics: none
navigation:
  - title: Base
    url: base/
