---
# Jekyll settings
permalink: pretty
markdown: kramdown


# Excluded files
exclude:
- Gem*
- "*.lock"
- "*rb"
- ".git*"
- "*.md"
- "*.json"
- node_modules
- gulp*
- ".jekyll-metadata"
- ".*"


# Site info
author: Dieter Peirs
title: Inuit boilerplate
timezone: UTC
description: A Jekyll boilerplate.
url: none
email: none
twitter_username: DieterPeirs
github_username: dietr
dribbble_username: DieterPeirs
medium_username: "@DieterPeirs"
google_analytics: none


# Site navigation
navigation:
  - title: About
    url: About/


# Collections
# collections:
#   collection:
#     title: Collection
#     output: true
